import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/Navigation'
import {Space_Grotesk} from '@next/font/google'

const font = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ['latin'],
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>🚀</title>
      </head>
      <body className={font.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
